# Stage 09 — Homework Starter Notebook

In the lecture, we learned how to create engineered features. Now it’s your turn to apply those ideas to your own project data.

In [1]:
import pandas as pd
import numpy as np

# Example synthetic data (replace with your project dataset)
np.random.seed(0)
n = 100
df = pd.DataFrame({
    'income': np.random.normal(60000, 15000, n).astype(int),
    'monthly_spend': np.random.normal(2000, 600, n).astype(int),
    'credit_score': np.random.normal(680, 50, n).astype(int)
})
df.head()

   income  monthly_spend  credit_score
0   86460           3129           661
1   66002           1191           668
2   74681           1237           734
3   93613           2581           712
4   88013           1296           712

## TODO: Implement at least 2 engineered features here

In [2]:
def create_features(df):
    """
    Create engineered features for modeling.
    Assumptions:
    - Rolling mean of spending captures short-term trends.
    - Spend-to-income ratio helps normalize across different income levels.
    """
    df['spend_income_ratio'] = df['monthly_spend'] / df['income']
    df['rolling_spend_mean'] = df['monthly_spend'].rolling(3).mean().fillna(df['monthly_spend'])
    return df

df = create_features(df)
df.head()

   income  monthly_spend  credit_score  spend_income_ratio  rolling_spend_mean
0   86460           3129           661            0.036190         3129.000000
1   66002           1191           668            0.018045         1191.000000
2   74681           1237           734            0.016564         1852.333333
3   93613           2581           712            0.027571         1669.666667
4   88013           1296           712            0.014725         1704.666667

### Rationale for Feature 1: spend_income_ratio

The `spend_income_ratio` feature measures how much of a customer's income is spent each month. 

**Why it may help a model:**
- During EDA, we observed that `income` and `spend` are both right-skewed, and their absolute values vary widely across customers.
- Directly using `monthly_spend` may bias the model toward high-income individuals who naturally spend more.
- By normalizing spending relative to income, `spend_income_ratio` allows the model to identify **high-spending behavior relative to each individual's means**, rather than absolute spending levels.
- This can improve model performance when predicting customer behavior or segmenting high-value users, as it captures consumption intensity rather than raw spend.

### Rationale for Feature 2: rolling_spend_mean

The `rolling_spend_mean` feature calculates the 3-month rolling average of monthly spending.

**Why it may help a model:**
- During EDA, we observed that `monthly_spend` can fluctuate significantly month-to-month, including occasional spikes or drops.
- Using the raw `monthly_spend` directly might introduce noise and make the model sensitive to short-term volatility.
- The rolling mean smooths out these fluctuations, capturing **short-term spending trends** and providing a more stable signal of customer behavior.
- This can help the model better identify patterns in spending over time, improving predictions and reducing overreaction to outlier months.