# Setup: Generate Sample Dataset

This cell creates the required folder structure (`data/raw/` and `data/processed/`) relative to the notebook, and generates the sample CSV dataset with missing values. 
This ensures the dataset is ready for cleaning functions and saves it to `data/raw/sample_data.csv`.

In [18]:
import os
import pandas as pd
import numpy as np

# Define folder paths relative to this notebook
raw_dir = 'data/raw'
processed_dir = 'data/processed'

# Create folders if they don't exist
os.makedirs(raw_dir, exist_ok=True)
os.makedirs(processed_dir, exist_ok=True)

# Define the sample data
data = {
    'age': [34, 45, 29, 50, 38, np.nan, 41],
    'income': [55000, np.nan, 42000, 58000, np.nan, np.nan, 49000],
    'score': [0.82, 0.91, np.nan, 0.76, 0.88, 0.65, 0.79],
    'zipcode': ['90210', '10001', '60614', '94103', '73301', '12345', '94105'],
    'city': ['Beverly', 'New York', 'Chicago', 'SF', 'Austin', 'Unknown', 'San Francisco'],
    'extra_data': [np.nan, 42, np.nan, np.nan, np.nan, 5, np.nan]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV in raw data folder
csv_path = os.path.join(raw_dir, 'sample_data.csv')
if not os.path.exists(csv_path):
    df.to_csv(csv_path, index=False)
    print(f'Sample dataset created and saved to {csv_path}')
else:
    print(f'File already exists at {csv_path}. Skipping CSV creation to avoid overwrite.')

File already exists at data/raw\sample_data.csv. Skipping CSV creation to avoid overwrite.

# Homework Starter — Stage 6: Data Preprocessing
Use this notebook to apply your cleaning functions and save processed data.

In [25]:
import pandas as pd
import numpy as np
from src import cleaning

## Load Raw Dataset

In [26]:
df = pd.read_csv('data/raw/sample_data.csv')
df.head()

    age   income  score  zipcode      city  extra_data
0  34.0  55000.0   0.82    90210   Beverly         NaN
1  45.0      NaN   0.91    10001  New York        42.0
2  29.0  42000.0    NaN    60614   Chicago         NaN
3  50.0  58000.0   0.76    94103        SF         NaN
4  38.0      NaN   0.88    73301    Austin         NaN

## Apply Cleaning Functions

In [27]:
# TODO: Apply your functions here
from src.cleaning import fill_missing_median, drop_missing, normalize_data
df_cleaned = df.copy()
df_cleaned = fill_missing_median(df_cleaned,['age','income','score'])
df_cleaned.head()
# Example:
# df = cleaning.fill_missing_median(df, ['col1','col2'])
# df = cleaning.drop_missing(df, threshold=0.5)
# df = cleaning.normalize_data(df, ['col1','col2'])

    age   income  score  zipcode      city  extra_data
0  34.0  55000.0  0.820    90210   Beverly         NaN
1  45.0  52000.0  0.910    10001  New York        42.0
2  29.0  42000.0  0.805    60614   Chicago         NaN
3  50.0  58000.0  0.760    94103        SF         NaN
4  38.0  52000.0  0.880    73301    Austin         NaN

In [28]:
df_cleaned = drop_missing(df_cleaned, threshold=0.5)
df_cleaned.head()

    age   income  score  zipcode      city  extra_data
0  34.0  55000.0  0.820    90210   Beverly         NaN
1  45.0  52000.0  0.910    10001  New York        42.0
2  29.0  42000.0  0.805    60614   Chicago         NaN
3  50.0  58000.0  0.760    94103        SF         NaN
4  38.0  52000.0  0.880    73301    Austin         NaN

In [30]:
import importlib
import src.cleaning as cleaning
importlib.reload(cleaning)

In [31]:
df_cleaned = normalize_data(df_cleaned)
df_cleaned.head()

        age  income     score   zipcode      city  extra_data
0  0.238095  0.8125  0.653846  0.953688   Beverly         NaN
1  0.761905  0.6250  1.000000  0.000000  New York         1.0
2  0.000000  0.0000  0.596154  0.601791   Chicago         NaN
3  1.000000  1.0000  0.423077  0.999976        SF         NaN
4  0.428571  0.6250  0.884615  0.752640    Austin         NaN

## Save Cleaned Dataset

In [32]:
df.to_csv('data/processed/sample_data_cleaned.csv', index=False)

##  Compare original vs cleaned data

In [34]:
def compare_original_vs_cleaned(original: pd.DataFrame, cleaned: pd.DataFrame):
    """
    Compare original vs cleaned DataFrame.
    Prints shape, missing values, column types, and basic stats.
    """
    print("===== Shape =====")
    print("Original shape:", original.shape)
    print("Cleaned shape :", cleaned.shape)
    
    print("\n===== Missing Values =====")
    print("Original missing values:\n", original.isna().sum())
    print("Cleaned missing values:\n", cleaned.isna().sum())
    
    print("\n===== Column Types =====")
    print("Original dtypes:\n", original.dtypes)
    print("Cleaned dtypes:\n", cleaned.dtypes)
    
    print("\n===== Descriptive Statistics =====")
    print("Original:\n", original.describe())
    print("Cleaned:\n", cleaned.describe())
    
    print("\n===== Head (first 5 rows) =====")
    print("Original:\n", original.head())
    print("Cleaned:\n", cleaned.head())

In [35]:
compare_original_vs_cleaned(df, df_cleaned)

===== Shape =====
Original shape: (7, 6)
Cleaned shape : (7, 6)

===== Missing Values =====
Original missing values:
 age           1
income        3
score         1
zipcode       0
city          0
extra_data    5
dtype: int64
Cleaned missing values:
 age           0
income        0
score         0
zipcode       0
city          0
extra_data    5
dtype: int64

===== Column Types =====
Original dtypes:
 age           float64
income        float64
score         float64
zipcode         int64
city           object
extra_data    float64
dtype: object
Cleaned dtypes:
 age           float64
income        float64
score         float64
zipcode       float64
city           object
extra_data    float64
dtype: object

===== Descriptive Statistics =====
Original:
              age        income     score      zipcode  extra_data
count   6.000000      4.000000  6.000000      7.00000    2.000000
mean   39.500000  51000.000000  0.801667  62097.00000   23.500000
std     7.556454   7071.067812  0.092826  36869.63632   26.162951
min    29.000000  42000.000000  0.650000  10001.00000    5.000000
25%    35.000000  47250.000000  0.767500  36479.50000   14.250000
50%    39.500000  52000.000000  0.805000  73301.00000   23.500000
75%    44.000000  55750.000000  0.865000  92156.50000   32.750000
max    50.000000  58000.000000  0.910000  94105.00000   42.000000
Cleaned:
             age    income     score   zipcode  extra_data
count  7.000000  7.000000  7.000000  7.000000    2.000000
mean   0.500000  0.589286  0.585165  0.619424    0.500000
std    0.328479  0.314281  0.325952  0.438381    0.707107
min    0.000000  0.000000  0.000000  0.000000    0.000000
25%    0.333333  0.531250  0.480769  0.314830    0.250000
50%    0.500000  0.625000  0.596154  0.752640    0.500000
75%    0.666667  0.718750  0.769231  0.976832    0.750000
max    1.000000  1.000000  1.000000  1.000000    1.000000

===== Head (first 5 rows) =====
Original:
     age   income  score  zipcode      city  extra_data
0  34.0  55000.0   0.82    90210   Beverly         NaN
1  45.0      NaN   0.91    10001  New York        42.0
2  29.0  42000.0    NaN    60614   Chicago         NaN
3  50.0  58000.0   0.76    94103        SF         NaN
4  38.0      NaN   0.88    73301    Austin         NaN
Cleaned:
         age  income     score   zipcode      city  extra_data
0  0.238095  0.8125  0.653846  0.953688   Beverly         NaN
1  0.761905  0.6250  1.000000  0.000000  New York         1.0
2  0.000000  0.0000  0.596154  0.601791   Chicago         NaN
3  1.000000  1.0000  0.423077  0.999976        SF         NaN
4  0.428571  0.6250  0.884615  0.752640    Austin         NaN

## Preprocessing Assumptions

When we clean and preprocess data, every choice encodes assumptions about the dataset. It's important to document these for reproducibility and stakeholder understanding.

### 1. Missing Data Handling
- Filling missing numeric values with median assumes the missingness is **MCAR or MAR** (not systematically biased).  
- Forward/backward fill assumes **temporal continuity** in time series data.  
- Dropping rows assumes the missing rows are **not critical** to analysis.  
- Imputation affects averages, distributions, and model training.

### 2. Understanding Missingness
- MCAR: safe to drop or fill, assumes randomness.  
- MAR: imputation using related features is valid.  
- MNAR: missing depends on unobserved values; may require domain knowledge.  
- Misidentifying missingness can bias results.

### 3. Filtering / Data Cleaning
- Removing negative or out-of-range values assumes they are **errors or invalid entries**.  
- Dropping columns or rows with excessive missingness assumes those data are **non-essential**.  
- Rare but valid events might be lost if thresholds are too strict.

### 4. Scaling / Normalization
- StandardScaler assumes features are roughly **normally distributed**.  
- MinMaxScaler assumes min and max values are **representative**, not extreme outliers.  
- Scaling changes interpretation of magnitudes; coefficients or distances may be affected.

### 5. Column Type Corrections
- Converting strings to numeric assumes there are **no hidden characters or formatting issues**.  
- Parsing dates assumes a **consistent date format**.  
- Categoricals assume a **finite, discrete set of values**.  
- Wrong types can break computations or modeling.

### 6. Reproducibility & Modularity
- Using modular functions assumes **future datasets follow similar structure and patterns**.  
- Documenting assumptions ensures that preprocessing is **transparent** and results are interpretable.